spring.application.name=app


# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/mywalletDB
spring.datasource.username=expense_user
spring.datasource.password=test
spring.datasource.driver-class-name=org.postgresql.Driver

# spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.open-in-view=false

spring.flyway.enabled=false
